services:

  user-service:
    build: 
      context: ./user-service
      dockerfile: Dockerfile
    container_name: user-service
    ports:
      - "8080:8080"
    env_file:
      - ./user-service/.env
    depends_on:
      - user-db
      - rabbitmq

  user-db:
    image: postgres:16
    container_name: user-db
    restart: always
    env_file:
      - ./user-service/.env
    ports:
      - "5433:5432"              
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin 

  user-receiver:
    build: ./user-receiver
    environment:
      RABBITMQ_URL: "amqp://admin:admin@rabbitmq:5672/"
      PORT: 3000
    depends_on:
      - rabbitmq
    ports:
      - "3000:3000"


volumes:
  postgres_data:
